# Generated by Django 5.2.4 on 2025-08-28 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_hora_termino', models.DateTimeField(blank=True, null=True)),
                ('numero_bi', models.CharField(max_length=30)),
                ('numero_bo', models.CharField(max_length=30)),
                ('classificacao', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=255)),
                ('historico', models.TextField()),
                ('relatornome', models.CharField(max_length=255)),
                ('relatordocumento', models.CharField(max_length=50)),
                ('autoridadenome', models.CharField(max_length=255)),
                ('autoridadedocumento', models.CharField(max_length=50)),
                ('endereco_dofato', models.CharField(max_length=255)),
                ('numero_dofato', models.CharField(max_length=20)),
                ('bairro_dofato', models.CharField(max_length=100)),
                ('orgao', models.CharField(max_length=100)),
                ('secao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Envolvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('naturalidade', models.CharField(max_length=100)),
                ('datanascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('estadocivil', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('identidade', models.CharField(max_length=20)),
                ('profissao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('escolaridade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BoletimEnvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envolvimento', models.CharField(choices=[('SOLICITANTE', 'Solicitante'), ('VITIMA', 'Vítima'), ('AUTOR', 'Autor'), ('TESTEMUNHA', 'Testemunha'), ('SOLICITANTE_VITIMA', 'Solicitante/Vítima'), ('SOLICITANTE_AUTOR', 'Solicitante/Autor'), ('SOLICITANTE_TESTEMUNHA', 'Solicitante/Testemunha')], max_length=30)),
                ('boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.boletim')),
                ('envolvido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.envolvido')),
            ],
        ),
    ]
